Repository auth0/cosmos, pull requests merged in 2018-08, with the labels that each got.

#757 End support for uncontrolled state in Tabs
  core/components/molecules/tabs/tabs.js
  core/components/molecules/tabs/tabs.md
  core/components/molecules/tabs/tabs.story.js
Labels: ⚠️high priority, 💔breaking change, 🖥️api / dx

#752 Proposal: Use standard prettier config to improve IDE plugin compatibility.
  package.json
Labels: ⚡enhancement, 💬discussion, 🛠️tooling

#762 Remove label from button props in actions
  core/components/molecules/form/actions/actions.js
Labels: 🐞bug

#750 Pagination components improvements
  core/components/_helpers/pagination.js
  core/components/atoms/icon/icons.json
  core/components/molecules/pager/pager.js
  core/components/molecules/pager/pager.md
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.md
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
  core/components/molecules/pagination/pagination.js
  core/components/molecules/pagination/pagination.md
Labels: ⚡enhancement, 🎨styling, 🖼️design / ux

#758 Automatic sorting for Table
  core/components/atoms/button/stories/wrapping.story.js
  core/components/atoms/icon/icons.json
  core/components/molecules/pager/pager.js
  core/components/molecules/table/table-column.js
  core/components/molecules/table/table-header.js
  core/components/molecules/table/table.js
  core/components/molecules/table/table.md
  core/components/molecules/table/table.sketch.js
  core/components/molecules/table/table.story.js
Labels: ✋don't merge, 💔breaking change

#783 Fix Tabs examples
  examples/manage/pages/application-detail/index.js
  internal/docs/overview/examples/tabs.js
Labels: ☂️example app, ⚠️high priority, 🐞bug

#784 Fix manage stories
  examples/manage/components/page.js
  examples/manage/index.js
  examples/manage/manage.story.js
  examples/manage/pages/application-detail/index.js
Labels: 🐞bug, 👮testing

#810 Fix bug in Avatar block with link option
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/avatar-block/avatar-block.story.js
Labels: 🎨styling, 🐞bug

#782 Support free texts in Page Header, Empty State and Alert.
  core/components/_helpers/free-text.js
  core/components/_helpers/page-header.js
  core/components/atoms/alert/alert.js
  core/components/atoms/alert/alert.md
  core/components/atoms/alert/alert.story.js
  core/components/molecules/empty-state/empty-state.js
  core/components/molecules/empty-state/empty-state.md
  core/components/molecules/form/field/field.js
  core/components/molecules/page-header/description.js
  core/components/molecules/page-header/page-header.js
  core/components/molecules/page-header/page-header.md
  core/components/molecules/page-header/page-header.story.js
  internal/docs/spec/page-header.js
Labels: ⚡enhancement, 🖥️api / dx

#786 Input color change in the tokens
  core/tokens/colors.js
Labels: ✋don't merge

#814 Insert globals before everything else + missing fonts
  core/components/_helpers/globals.js
  core/components/atoms/icon/icons.json
Labels: 🐞bug, 👮testing

#790 Do not require form's primary action handler
  core/components/_helpers/action-shape.js
  core/components/molecules/form/actions/actions.js
Labels: ☂️feedback, ⚡enhancement, 🖥️api / dx

#834 Website: Fix nav version in navigation
  .travis.yml
Labels: 🐞bug, 📚docs

#836 Replace avatar links with something more permanent
  core/components/molecules/table/table.md
Labels: 🐞bug, 📚docs

#835 Fix icon file silliness
  core/components/atoms/icon/icons.json
  package.json
Labels: 🐞bug, 🛠️tooling

#822 Update Page Header API usage in Manage example
  examples/manage/pages/anomaly-detection/index.js
  examples/manage/pages/apis/index.js
  examples/manage/pages/applications/index.js
  examples/manage/pages/emails/index.js
  examples/manage/pages/rules/index.js
  examples/manage/pages/slogs/index.js
  examples/manage/pages/users/index.js
  examples/manage/pages/welcome/index.js
Labels: ☂️example app

#844 Fix #808: Fix learn more hover ignores the arrow icon
  core/components/molecules/page-header/description.js
Labels: 🎨styling, 🐞bug

#852 Add deprecated tag in docs
  core/components/atoms/alert/alert.js
  core/components/atoms/text-input/text-input.js
  internal/docs/docs-components/tag.js
  internal/docs/spec/props.js
Labels: 📚docs, 🙋‍♀️feature-request

#845 Pagination toolbar: disable buttons on edge pages & hide on one page
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.md
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
Labels: ⚡enhancement, 🎨styling

#876 Docs: Fix production version + implement caching
  .travis.yml
  core/babel-preset/package.json
  core/components/package.json
  core/engine/configs/webpack.development.config.js
  core/engine/configs/webpack.production.config.js
  core/engine/package.json
  core/tokens/package.json
  examples/manage/package.json
  examples/perf-tests/package.json
  examples/webpack-hello-world/package.json
  internal/docs/package.json
  internal/docs/public/index.html
  package-scripts.js
  yarn.lock
Labels: 📚docs, 🛠️tooling
