Repository auth0/cosmos, pull requests merged in 2018-10, with the labels that each got.

#957 Run prettier on generated icons
  package-scripts.js
  package.json
  tooling/update-icons.js
  yarn.lock
Labels: 🛠️tooling

#958 More prominent version switcher for docs
  internal/docs/docs-components/navigation.js
  internal/docs/docs-components/version-switcher.js
Labels: release: patch

#982 Add example for actions in table
  core/components/molecules/table/table.md
Labels: ⚡enhancement, 📦component:table

#983 Use avatar block for name fields in Table docs
  core/components/molecules/table/table.md
Labels: ⚡enhancement, 📚docs, 📦component:table

#978 Introduce table loading states
  core/components/molecules/table/table.js
  core/components/molecules/table/table.md
  core/components/molecules/table/table.story.js
  internal/test/snapshot/__snapshots__/table.test.js.snap
  internal/test/unit/__snapshots__/table.test.js.snap
Labels: release: minor, ⚡enhancement, 📦component:table

#959 Tooltip in button group UI fixes + Tooltip stories
  .travis.yml
  core/components/atoms/button/button.js
  core/components/atoms/tooltip/tooltip.js
  core/components/atoms/tooltip/tooltip.story.js
  core/components/molecules/button-group/button-group.js
  internal/test/snapshot/__snapshots__/alert.test.js.snap
  internal/test/snapshot/__snapshots__/button-group.test.js.snap
  internal/test/snapshot/__snapshots__/page-header.test.js.snap
  internal/test/snapshot/__snapshots__/pagination-toolbar.test.js.snap
  internal/test/snapshot/__snapshots__/resource-list.test.js.snap
  internal/test/snapshot/__snapshots__/table.test.js.snap
  package-scripts.js
Labels: release: patch, 🐞bug, 👮testing, 🖼️design / ux

#984 Add "more" icon
  core/components/atoms/icon/icons.json
  core/icons/icon-more.svg
Labels: ⚡enhancement

#970 Add pagination helper tests
  internal/test/unit/pagination.test.js
Labels: 👮testing

#964 Fix "Hello World" message
  examples/webpack-hello-world/index.js
Labels: 🎃 hacktoberfest

#999 Made secondary button's border darker
  core/tokens/colors.js
Labels: 🎃 hacktoberfest

#961 Add accesibility to Tabs
  core/components/molecules/tabs/tabs.js
  internal/test/unit/__snapshots__/tabs.test.js.snap
Labels: 🎃 hacktoberfest

#995 Fix sidebar scrolling in Firefox (fixes #994)
  internal/docs/app.js
  internal/docs/sidebar/index.js
Labels: 🎃 hacktoberfest

#975 Makes the list HTML semantically correct
  core/components/molecules/list/list.js
Labels: 🎃 hacktoberfest

#960 Made checkbox, radio and switch accessible with a keyboard
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/radio/radio.js
  core/components/atoms/switch/switch.js
  readme.md
Labels: release: patch, 🎃 hacktoberfest

#966 Make Alert in docs non-dismissable
  internal/docs/spec/page-header.js
Labels: 🎃 hacktoberfest

#963 Match alert close button styling to styleguide - Issue #942
  core/components/atoms/alert/alert.js
Labels: 🎃 hacktoberfest

#1029 Made checkbox, radio and switch accessible with a keyboard via @DCzajkowski
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/radio/radio.js
  core/components/atoms/switch/switch.js
  readme.md
Labels: 🎃 hacktoberfest

#962 Fix Form.Radio example does not working on docs
  core/components/molecules/form/field/field.md
  core/components/molecules/form/form.md
Labels: 🎃 hacktoberfest

#992 Table columns can now be passed as external children
  core/components/molecules/table/table.js
  core/components/molecules/table/table.story.js
Labels: 🎃 hacktoberfest

#1046 remove line-height from story stack as well
  core/components/_helpers/story-stack.js
Labels: 👮testing

#1047 Tests: stack item should inherit line height
  core/components/_helpers/story-stack.js
Labels: 👮testing

#1051 Pagination toolbar: Hide toolbar if there are zero items by @astanciu
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
Labels: 🐞bug

#1039 Improve readme with material from docs website
  readme.md
Labels: 🎃 hacktoberfest
