Repository auth0/cosmos, pull requests merged in 2018-07, with the labels that each got.

#646 Update PoC link in docs
  internal/docs/home.js
Labels: 🐞bug, 📚docs

#647 Support for ResourceListItem disabled actions
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/resource-list/item/item.md
Labels: 🖥️api / dx

#629 Docs: Add styled usage (Revive #610)
  internal/docs/app.js
  internal/docs/home.js
  internal/docs/sidebar/list.js
  internal/docs/usage.js
Labels: ⚡enhancement, 📚docs

#660 #658: Support raw buttons as dialog action attributes.
  core/components/molecules/dialog/dialog.js
  core/components/molecules/dialog/dialog.md
Labels: ⚡enhancement, 🖥️api / dx

#686 Make the sidebar foldable
  internal/docs/app.js
Labels: ⚡enhancement, 📚docs

#687 Docs: Make search case insensitive
  internal/docs/sidebar/index.js
Labels: ⚡enhancement, 🐞bug, 📚docs

#688 Add dismissal features to alert
  core/components/atoms/alert/alert.js
  core/components/atoms/alert/alert.md
  internal/docs/spec/prop-string.js
Labels: ⚡enhancement, 🖥️api / dx

#690 Replace input error prop with hasError
  core/components/_helpers/custom-validations.js
  core/components/atoms/_styled-input/_styled-input.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/textarea/textarea.js
  core/components/molecules/form/field/field.js
  core/components/molecules/form/field/field.md
Labels: ⚡enhancement, 💔breaking change, 🖥️api / dx

#666 WIP: Pagination component base
  core/components/_helpers/pagination.js
  core/components/components.js
  core/components/index.js
  core/components/molecules/pager/index.js
  core/components/molecules/pager/pager.js
  core/components/molecules/pager/pager.md
  core/components/molecules/pager/pager.story.js
  core/components/molecules/pagination-toolbar/index.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.md
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
  core/components/molecules/pagination/index.js
  core/components/molecules/pagination/pagination.js
  core/components/molecules/pagination/pagination.md
  core/components/molecules/pagination/pagination.story.js
Labels: ✋don't merge

#694 Docs: Scroll to top on page change
  internal/docs/app.js
Labels: ⚡enhancement, 📚docs

#689 Engine 0.2: Add error overlay
  core/engine/configs/webpack.dev.config.js
  core/engine/package.json
  core/engine/utils/prop-type-errors.js
  yarn.lock
Labels: ⚡enhancement, 🐞bug, 🖥️api / dx, 🛠️tooling

#698 Move overview inside docs
  internal/docs/app.js
  internal/docs/home.js
  internal/docs/overview/components/container.js
  internal/docs/overview/components/example.js
  internal/docs/overview/components/grid.js
  internal/docs/overview/components/section.js
  internal/docs/overview/components/stack.js
  internal/docs/overview/examples/avatar-blocks.js
  internal/docs/overview/examples/avatars.js
  internal/docs/overview/examples/badges.js
  internal/docs/overview/examples/buttons-inputs.js
  internal/docs/overview/examples/buttons.js
  internal/docs/overview/examples/colors.js
  internal/docs/overview/examples/dialogs.js
  internal/docs/overview/examples/empty-states.js
  internal/docs/overview/examples/forms.js
  internal/docs/overview/examples/icons.js
  internal/docs/overview/examples/inputs.js
  internal/docs/overview/examples/labels.js
  internal/docs/overview/examples/lists.js
  internal/docs/overview/examples/logos.js
  internal/docs/overview/examples/page-headers.js
  internal/docs/overview/examples/resource-lists.js
  internal/docs/overview/examples/spacing.js
  internal/docs/overview/examples/tables.js
  internal/docs/overview/examples/tabs.js
  internal/docs/overview/examples/tags.js
  internal/docs/overview/examples/tooltip.js
  internal/docs/overview/examples/typography.js
  internal/docs/overview/index.js
  internal/docs/overview/public/index.html
  internal/docs/overview/public/main.js
  internal/docs/sidebar/list.js
  internal/docs/usage.js
  internal/overview/app.js
  internal/overview/components/icon-sketch.js
  internal/overview/components/navigation.js
  internal/overview/components/overview.js
  internal/overview/index.js
  internal/overview/package.json
  internal/overview/webpack.config.js
  internal/redirect/index.html
  package-scripts.js
Labels: ⚡enhancement, 🛠️tooling

#701 Fix styled export
  core/components/styled.js
Labels: 🐞bug

#714 Support text in loading + success
  core/components/atoms/button/button.js
  core/components/atoms/button/button.md
  core/components/atoms/spinner/index.js
  core/components/atoms/spinner/spinner.js
Labels: 🖥️api / dx

#718 Form actions pass props through
  core/components/molecules/form/actions/actions.js
  core/components/molecules/form/actions/actions.md
Labels: ☂️feedback

#737 Add Manage PoC to chromatic tests
  .storybook/config.js
  examples/manage/components/page.js
  examples/manage/index.js
  examples/manage/manage.story.js
Labels: 👮testing

#746 Manage PoC: fix all prop warnings
  core/components/molecules/resource-list/item/item.js
  examples/manage/components/top-navigation.js
  examples/manage/pages/apis/index.js
  examples/manage/pages/application-detail/advanced.js
  examples/manage/pages/application-detail/connections.json
  examples/manage/pages/rules/index.js
  examples/manage/pages/users/index.js
Labels: ☂️example app, 🐞bug, 🖥️api / dx

#738 Add document playground for folks to report issues
  internal/docs/app.js
  internal/docs/home.js
  internal/docs/playground.js
  internal/docs/sidebar/list.js
  internal/docs/spec/playground.js
Labels: 🛠️tooling
