Repository auth0/cosmos, pull requests merged in 2018-09, with the labels that each got.

#851 Add styled components plugin
  core/babel-preset/dev.js
  core/babel-preset/package.json
  core/components/_helpers/automation-attribute.js
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/link/link.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/textarea/textarea.js
  core/components/molecules/button-group/button-group.js
  core/components/molecules/danger-zone/index.js
  core/components/molecules/form/field/field.js
  core/components/molecules/list/list.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.md
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
  core/components/molecules/pagination/pagination.js
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/sidebar/sidebar-link.js
  core/components/molecules/stack/stack.js
  core/components/molecules/table/table.js
  core/components/molecules/table/table.md
  core/engine/configs/webpack.development.config.js
  package-scripts.js
  yarn.lock
Labels: 🛠️tooling

#771 Support target in link for EmptyState and AvatarBlock
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/avatar-block/avatar-block.md
  core/components/molecules/empty-state/empty-state.js
  core/components/molecules/empty-state/empty-state.md
  examples/manage/components/side-navigation.js
  examples/manage/pages/sso-integrations/index.js
  internal/docs/spec/prop-string.js
  internal/docs/spec/prop-type.js
Labels: ☂️feedback, 🖥️api / dx

#881 Exit early for already published release
  tooling/publish.js
Labels: 🐞bug, 🛠️tooling

#903 Disable babel-sc plugin until we fix targetting problem
  core/babel-preset/dev.js
Labels: 🐞bug

#909 Add pull request templates
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/component_work.md
Labels: 🛠️tooling

#849 Allow table to receive an empty state instance and show it if no items are present
  core/components/molecules/table/table.js
  core/components/molecules/table/table.md
  core/components/molecules/table/table.story.js
Labels: 📦component:table

#933 README: change to absolute path
  readme.md
Labels: 🐞bug

#928 Chromatic: add auto-accept-changes-on-master
  package-scripts.js
Labels: 🛠️tooling

#919 Alerts: Add support for icons
  core/components/atoms/alert/alert.js
  core/components/atoms/alert/alert.md
  core/components/atoms/alert/alert.story.js
  core/components/atoms/icon/icons.json
  core/icons/icon-check-circle.svg
  core/icons/icon-danger.svg
  core/icons/icon-megaphone.svg
  core/icons/icon-notes.svg
  core/icons/icon-warning.svg
  core/tokens/colors.js
Labels: 📦 component, 🙋‍♀️feature-request

#946 Version switcher: Format the url correctly
  internal/docs/docs-components/version-switcher.js
Labels: 🐞bug

#930 Alert: doesn't break with no children/text
  core/components/_helpers/free-text.js
  core/components/_helpers/story-helpers.js
  core/components/atoms/alert/alert.story.js
Labels: 🐞bug

#948 Docs: Fix component search + Search through guides
  internal/docs/sidebar/children.js
  internal/docs/sidebar/index.js
  internal/docs/sidebar/list.js
Labels: 📚docs

#950 Fix docs props warnings for docs + sandbox
  core/components/atoms/alert/alert.js
  core/components/atoms/avatar/avatar.md
  core/components/atoms/checkbox/checkbox.md
  core/components/atoms/checkbox/checkbox.story.js
  core/components/atoms/icon/icon.js
  core/components/atoms/icon/icon.story.js
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/avatar-block/avatar-block.story.js
  core/components/molecules/danger-zone/danger-zone.story.js
  core/components/molecules/dialog/dialog.js
  core/components/molecules/empty-state/empty-state.js
  core/components/molecules/tabs/tabs.story.js
  internal/docs/automation-glossary.js
  internal/docs/overview/examples/empty-states.js
  internal/docs/spec/prop-string.js
Labels: 🐞bug, 📚docs

#937 Add local styles for styleguide compatibility
  .storybook/webpack.config.js
  core/components/_helpers/free-text.js
  core/components/_helpers/globals.js
  core/components/atoms/alert/alert.js
  core/components/atoms/alert/alert.story.js
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/switch/switch.js
  core/components/atoms/text/text.js
  core/components/atoms/textarea/textarea.js
  core/components/molecules/danger-zone/danger-zone.js
  core/components/molecules/dialog/dialog.story.js
  core/components/molecules/empty-state/empty-state.js
  core/components/molecules/page-header/page-header.story.js
  internal/test/snapshot/__snapshots__/alert.test.js.snap
  internal/test/snapshot/__snapshots__/breadcrumb.test.js.snap
  internal/test/snapshot/__snapshots__/checkbox.test.js.snap
  internal/test/snapshot/__snapshots__/page-header.test.js.snap
  internal/test/snapshot/__snapshots__/pager.test.js.snap
  internal/test/snapshot/__snapshots__/pagination-toolbar.test.js.snap
  internal/test/snapshot/__snapshots__/pagination.test.js.snap
  internal/test/snapshot/__snapshots__/sidebar.test.js.snap
  internal/test/snapshot/__snapshots__/switch.test.js.snap
  internal/test/snapshot/__snapshots__/table.test.js.snap
  internal/test/snapshot/__snapshots__/text-area.test.js.snap
  internal/test/unit/__snapshots__/empty-state.test.js.snap
  internal/test/unit/empty-state.test.js
Labels: release: patch

#934 Allow to have nothing selected on Select
  core/components/atoms/select/select.js
  core/components/atoms/select/select.md
  core/components/atoms/select/select.story.js
  internal/test/snapshot/__snapshots__/select.test.js.snap
  internal/test/unit/automation-attributes.test.js
Labels: release: minor, ⚠️ high priority, ⚡enhancement, 🖼️design / ux

#954 Add placeholder story for select
  core/components/atoms/select/select.story.js
Labels: release: patch, 👮testing
