Repository auth0/cosmos, pull requests merged in 2018-03, with the labels that each got.

#343 Polish sections of the PoC
  src/components/molecules/page-header/description.js
  src/components/molecules/page-header/index.js
  src/manage/advanced.js
  src/manage/client-list.js
  src/manage/connections.js
  src/manage/index.js
  src/manage/settings.js
Labels: design/ux

#352 Use yarn instead of npm (step 1)
  .travis.yml
  package-lock.json
  package.json
  src/docs/contribution-guide.js
  yarn.lock
Labels: tooling

#353 Make components and tokens packages (step 2)
  .gitignore
  package.json
  src/components/package.json
  src/index.js
  src/is-cosmos-ready-yet/index.js
  src/tokens/package.json
  tooling/update-progress.js
Labels: tooling

#373 Manage poc org
  src/manage/components/client-avatar.js
  src/manage/components/client-types-images.js
  src/manage/components/page.js
  src/manage/pages/client-detail/advanced.js
  src/manage/pages/client-detail/connections.js
  src/manage/pages/client-detail/index.js
  src/manage/pages/client-detail/settings.js
  src/manage/pages/clients/create-client-dialog.js
  src/manage/pages/clients/index.js
  src/overview/examples/lists.js
  src/overview/examples/page-headers.js
Labels: ☂️example app

#385 Org page header
  src/components/molecules/page-header/index.js
  src/components/molecules/page-header/page-header.md
  src/manage/components/client-page-header.js
  src/manage/pages/client-detail/index.js
  src/manage/pages/clients/index.js
  src/overview/examples/page-headers.js
Labels: ☂️example app

#398 add avatar component
  src/components/atoms/avatar/avatar.md
  src/components/atoms/avatar/index.js
  src/components/index.js
Labels: ☂️example app

#399 Fix margin buttongroup
  src/components/molecules/button-group/index.js
  src/components/molecules/form/actions/index.js
Labels: ☂️example app

#401 implement avatar component
  src/manage/components/client-avatar.js
  src/manage/components/client-types-images.js
  src/manage/components/top-navigation.js
  src/manage/pages/client-detail/index.js
  src/manage/pages/clients/index.js
  src/overview/examples/lists.js
  src/overview/examples/page-headers.js
Labels: ☂️example app

#408 Replace intent with appearance in overview
  src/overview/examples/buttons.js
  src/overview/src/buttons.js
Labels: 🐞bug

#410 Hello world with webpack + cosmos
  examples/webpack-hello-world/.gitignore
  examples/webpack-hello-world/index.js
  examples/webpack-hello-world/package.json
  examples/webpack-hello-world/public/index.html
  examples/webpack-hello-world/webpack.config.js
  examples/webpack-hello-world/yarn.lock
  src/babel-preset/index.js
  src/babel-preset/package.json
Labels: 🛠️tooling

#411 nest preset inside cosmos/babel
  examples/webpack-hello-world/package.json
  examples/webpack-hello-world/webpack.config.js
  examples/webpack-hello-world/yarn.lock
  src/components/babel.js
  src/components/package.json
  yarn.lock
Labels: 🛠️tooling

#413 Fix preset packing
  src/babel-preset/package.json
  src/babel-preset/yarn.lock
  src/components/package.json
  yarn.lock
Labels: 🐞bug, 🛠️tooling

#392 Created a Text component with 2 possible text styles
  src/components/atoms/text/index.js
  src/components/index.js
  src/manage/pages/clients/index.js
  src/overview/examples/typography.js
Labels: ☂️api hardening, 🖥️api / dx

#404 New avatar prop
  src/components/atoms/avatar/avatar.md
  src/components/atoms/avatar/index.js
  src/components/atoms/image/image.md
  src/components/atoms/image/index.js
  src/components/atoms/thumbnail/index.js
  src/components/atoms/thumbnail/thumbnail.md
  src/components/index.js
  src/manage/components/top-navigation.js
  src/manage/pages/client-detail/index.js
  src/manage/pages/clients/index.js
  src/overview/examples/avatars.js
  src/overview/examples/lists.js
  src/overview/examples/page-headers.js
  src/overview/examples/thumbnails.js
  src/overview/index.js
  src/tokens/misc.js
Labels: ☂️example app

#429 Add dummy app for size testing
  examples/perf-tests/.gitignore
  examples/perf-tests/just-react.js
  examples/perf-tests/package.json
  examples/perf-tests/public/index.html
  examples/perf-tests/webpack.config.js
  examples/perf-tests/with-cosmos.js
  examples/perf-tests/with-part-cosmos.js
  examples/perf-tests/with-styled.js
  examples/perf-tests/yarn.lock
  src/components/package.json
Labels: 🛠️tooling

#437 Fix random bugs
  src/components/atoms/button/index.js
  src/manage/pages/clients/create-client-dialog.js
  src/manage/pages/clients/index.js
  src/overview/ov-components/stack.js
Labels: 🐞bug

#438 Create jenkinsfile for release
  Jenkinsfile
Labels: ✋don't merge

#436 Buttons styles (and tokens)
  src/components/atoms/button/button.md
  src/components/atoms/button/index.js
  src/tokens/colors.js
Labels: ♿accessibility, 🖼️design / ux

#434 Updated Empty States to use the CTA button
  src/components/molecules/empty-state/index.js
Labels: 🖼️design / ux

#449 Enable push events for travis
  .travis.yml
  package.json
  yarn.lock
Labels: 🛠️tooling
