Repository auth0/cosmos, pull requests merged in 2018-11, with the labels that each got.

#1035 Table columns can now be passed as external children via @sanketsingh24
  core/components/molecules/table/table.js
  core/components/molecules/table/table.story.js
Labels: 🎃 hacktoberfest

#947 Fix button vertical centering and introduce right icon alignment
  .github/PULL_REQUEST_TEMPLATE/component_work.md
  core/components/_helpers/default-prop-change.js
  core/components/atoms/alert/alert.story.js
  core/components/atoms/button/button.js
  core/components/atoms/button/stories/icon.story.js
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/icon/icon.js
  core/components/atoms/icon/icons.json
  core/components/atoms/logo/logo.story.js
  core/components/atoms/radio/radio.js
  core/components/atoms/spinner/spinner.md
  core/components/atoms/spinner/spinner.story.js
  core/components/atoms/tooltip/tooltip.story.js
  core/components/molecules/pager/pager.js
  core/components/molecules/pagination/pagination.js
  core/icons/icon-chevron-left.svg
  core/icons/icon-chevron-right.svg
  internal/docs/docs-components/hamburger-button.js
  internal/docs/sidebar/list.js
  internal/test/unit/__snapshots__/empty-state.test.js.snap
  internal/test/unit/__snapshots__/page-header.test.js.snap
  internal/test/unit/pagination.test.js
Labels: release: minor

#1055 Tabs focus styles
  core/components/molecules/tabs/tabs.js
Labels: release: minor, 🎨styling

#1037 [Table] Add accessibility to table header and table row.
  core/components/molecules/table/table-header.js
  core/components/molecules/table/table.js
  internal/test/unit/__snapshots__/table.test.js.snap
Labels: 🎃 hacktoberfest, 📦component:table

#1058 Build scripts should use production mode
  core/engine/configs/webpack.production.config.js
Labels: 🐞bug, 🛠️tooling

#1065 Rename current cosmos-engine to cosmos-scripts
  core/babel-preset/package.json
  core/components/package.json
  core/tokens/package.json
  examples/manage/package.json
  examples/manage/webpack.development.config.js
  examples/manage/webpack.production.config.js
  examples/perf-tests/package.json
  examples/webpack-hello-world/package.json
  internal/cosmos-scripts/build.js
  internal/cosmos-scripts/cli.js
  internal/cosmos-scripts/configs/webpack.development.config.js
  internal/cosmos-scripts/configs/webpack.production.config.js
  internal/cosmos-scripts/dev.js
  internal/cosmos-scripts/index.js
  internal/cosmos-scripts/package.json
  internal/cosmos-scripts/start.js
  internal/cosmos-scripts/task.js
  internal/cosmos-scripts/utils/config-loader.js
  internal/cosmos-scripts/utils/prop-type-errors.js
  internal/docs/package.json
  package.json
  tooling/catchup.js
  tooling/publish.js
  yarn.lock
Labels: 🛠️tooling

#1067 Select: Add disabled + disabled options + groups
  core/components/atoms/select/index.js
  core/components/atoms/select/select.js
  core/components/atoms/select/select.md
  core/components/atoms/select/select.story.js
Labels: release: minor, ⚡enhancement

#1076 Added more icons
  core/components/atoms/icon/icons.json
  core/icons/icon-arrow-down.svg
  core/icons/icon-arrow-up.svg
  core/icons/icon-chevron-up.svg
  core/icons/icon-search.svg
  core/icons/icon-usage.svg
  core/icons/icon-user-add.svg
  tooling/update-icons.js
Labels: release: minor, ⚡enhancement

#985 Avatar Fixes
  core/components/_helpers/avatar-url.js
  core/components/atoms/avatar/assets/EmptyUser.js
  core/components/atoms/avatar/avatar.js
  core/components/atoms/avatar/avatar.md
  core/components/atoms/avatar/avatar.story.js
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/avatar-block/avatar-block.md
  core/components/package.json
  yarn.lock
Labels: ⚡enhancement, 🎨styling, 👮testing, 📦component:avatar

#1038 feat: Added subtitle to page-header component
  core/components/molecules/page-header/page-header.js
  core/components/molecules/page-header/page-header.story.js
Labels: 🎃 hacktoberfest

#1079 Adds system guidelines to the docs
  internal/docs/app.js
  internal/docs/sidebar/list.js
  internal/docs/system-guidelines.js
Labels: 📚docs

#1095 Process icons with different float precision depending on each one needs
  core/components/atoms/icon/icons.json
  core/icons/compression-precisions.json
  tooling/update-icons.js
Labels: release: patch

#1093 Make default prop change warning to appear if there is not a value set for the prop
  core/components/_helpers/default-prop-change.js
Labels: release: patch

#1121 Improve tests for table
  core/components/molecules/table/table.story.js
Labels: 👮 testing

#1119 Docs: Removed links that can be found in the Top navigation
  internal/docs/sidebar/list.js
Labels: 📚docs

#1137 Upgrade Storybook
  package.json
  yarn.lock
Labels: 🚨hi priority

#1086 Add Auth0 Social Icons
  core/components/atoms/icon/icons.json
  core/icons/aliases.json
  core/icons/icon-message.svg
  core/icons/icon-protocol.svg
  core/icons/social/brand-amazon.svg
  core/icons/social/brand-aol.svg
  core/icons/social/brand-baidu.svg
  core/icons/social/brand-bitbucket.svg
  core/icons/social/brand-bitly.svg
  core/icons/social/brand-box.svg
  core/icons/social/brand-daccount.svg
  core/icons/social/brand-dropbox.svg
  core/icons/social/brand-dwolla.svg
  core/icons/social/brand-evernote.svg
  core/icons/social/brand-exact.svg
  core/icons/social/brand-facebook.svg
  core/icons/social/brand-fitbit.svg
  core/icons/social/brand-flickr.svg
  core/icons/social/brand-github.svg
  core/icons/social/brand-google.svg
  core/icons/social/brand-instagram.svg
  core/icons/social/brand-linkedin.svg
  core/icons/social/brand-microsoft.svg
  core/icons/social/brand-miicard.svg
  core/icons/social/brand-paypal.svg
  core/icons/social/brand-planningcenter.svg
  core/icons/social/brand-renren.svg
  core/icons/social/brand-salesforce.svg
  core/icons/social/brand-sharepoint.svg
  core/icons/social/brand-shopify.svg
  core/icons/social/brand-soundcloud.svg
  core/icons/social/brand-thecity.svg
  core/icons/social/brand-thirtysevensignals.svg
  core/icons/social/brand-twitter.svg
  core/icons/social/brand-vkontakte.svg
  core/icons/social/brand-wiebo.svg
  core/icons/social/brand-wordpress.svg
  core/icons/social/brand-yahoo.svg
  core/icons/social/brand-yammer.svg
  core/icons/social/brand-yandex.svg
Labels: ✋don't merge, 🚨hi priority

#1101 Truncate table cell text & Add Table.Column docs
  core/components/molecules/table/table-column.js
  core/components/molecules/table/table.js
  core/components/molecules/table/table.md
  core/components/molecules/table/table.story.js
  internal/docs/docs-components/table.js
  internal/docs/spec/example.js
  internal/docs/spec/props.js
  internal/test/unit/__snapshots__/table.test.js.snap
Labels: 🚀 release: minor, 🚨hi priority

#1136 Remove prop-types to typescript declarations module
  core/components/package.json
  package.json
  tooling/component-metadata.js
Labels: 🐞bug

#1102 Dialog component
  core/components/atoms/_overlay/index.js
  core/components/atoms/_overlay/overlay.js
  core/components/atoms/heading/heading.js
  core/components/atoms/heading/index.js
  core/components/atoms/icon/icons.json
  core/components/molecules/dialog/dialog.js
  core/components/molecules/dialog/dialog.md
  core/components/molecules/dialog/dialog.story.js
  core/components/package.json
  examples/manage/public/index.html
  examples/manage/public/main.c0661ec6cc3e99f5495f.js
  internal/docs/docs-components/navigation.js
  internal/docs/public/index.html
  internal/docs/public/main.6f68bec9e5108446d085.js
  internal/test/unit/automation-attributes.test.js
  yarn.lock
Labels: ♿ accessibility, 🐞bug, 🙋‍♀️ user-request, 🚀 release: minor, 🚨hi priority

#1178 Fixes anchor buttons
  core/components/atoms/button/button.js
Labels: 🐞bug, 🚨hi priority

#1180 Add tests for #1164
  core/components/atoms/button/stories/icon.story.js
  core/components/molecules/table/table.story.js
Labels: 👮 testing

#1184 Internal: Enable styled-components plugin for dev mode
  core/babel-preset/dev.js
Labels: 🛠️ tooling

#1185 Docs: Split contribution guide
  internal/docs/app.js
  internal/docs/contribution-guide.js
  internal/docs/docs-components/folding-section.js
  internal/docs/pages/automation-glossary.js
  internal/docs/pages/changes.js
  internal/docs/pages/contribution-guide.js
  internal/docs/pages/contribution-guide/architecture.js
  internal/docs/pages/contribution-guide/component-files.js
  internal/docs/pages/contribution-guide/line-height.js
  internal/docs/pages/contribution-guide/setup.js
  internal/docs/pages/contribution-guide/system-guidelines.js
  internal/docs/pages/contribution-guide/testing.js
  internal/docs/pages/faqs.js
  internal/docs/pages/guiding-principles.js
  internal/docs/pages/usage.js
  internal/docs/sidebar/list.js
  internal/docs/system-guidelines.js
Labels: 📚docs

#1186 Internal components: Remove some underscores
  core/components/atoms/_box/box.js
  core/components/atoms/_box/box.md
  core/components/atoms/_box/index.js
  core/components/atoms/_styled-input/index.js
  core/components/atoms/_styled-input/styled-input.js
  core/components/atoms/_well/index.js
  core/components/atoms/_well/well.js
  core/components/atoms/_well/well.md
  core/components/molecules/_action-input/action-input.js
  core/components/molecules/_action-input/action-input.md
  core/components/molecules/_action-input/index.js
  tooling/component-metadata.js
Labels: 🛠️ tooling

#1133 Support buttons as resource list item actions
  core/components/_helpers/custom-validations.js
  core/components/atoms/button/button.js
  core/components/molecules/resource-list/action-builder.js
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/resource-list/item/item.md
  core/components/molecules/resource-list/resource-list.js
  core/components/molecules/resource-list/resource-list.md
  core/components/molecules/resource-list/resource-list.story.js
  internal/test/unit/resource-list.test.js
Labels: ⚠️ release: deprecation, 🖥️api / dx, 🙋‍♀️ user-request

#1172 Button: Add type prop + Use it in secondary Form.Actions
  core/components/atoms/button/button.js
  core/components/molecules/form/actions/actions.js
Labels: 🐞bug, 🖥️api / dx, 🙋‍♀️ user-request, 🚨hi priority

#1168 Added a paragraph story to test styles (link, strong, code)
  core/components/atoms/paragraph/paragraph.story.js
Labels: 👮 testing
