Repository auth0/cosmos, pull requests merged in 2018-05, with the labels that each got.

#520 Added additional pages to the PoC to be able to test components
  src/manage/components/page.js
  src/manage/components/side-navigation.js
  src/manage/pages/anomaly-detection/index.js
  src/manage/pages/apis/index.js
  src/manage/pages/clients/index.js
  src/manage/pages/rules/index.js
  src/manage/pages/slogs/index.js
  src/manage/pages/sso-integrations/index.js
  src/manage/pages/users/index.js
Labels: ☂️example app

#529 Fix persistent warning in Form.Actions
  src/components/molecules/button-group/index.js
Labels: 🐞bug

#533 Add defaults and * (required) to props table
  src/components/molecules/resource-list/item/item.md
  src/docs/docs-components/tag.js
  src/docs/sidebar/link.js
  src/docs/spec/default-props.js
  src/docs/spec/props.js
  tooling/component-metadata.js
  tooling/get-metadata.js
Labels: 📚docs

#534 Small improvements to alert component
  src/components/atoms/alert/alert.md
  src/components/atoms/alert/index.js
  src/components/index.js
Labels: ⚡enhancement, 📚docs

#491 Add {props} to emptyState example
  src/components/molecules/empty-state/empty-state.md
  src/docs/spec/get-defaults-from-code.js
Labels: ⚡enhancement, 📚docs

#558 Add missing id to switch (accessibility)
  src/components/atoms/switch/switch.js
Labels: 🐞bug

#552 Add bottom margin to Form.Actions
  src/components/molecules/form/actions/actions.js
  src/components/molecules/form/form.md
Labels: ⚡enhancement, 🖼️design / ux

#551 Replace method with handler
  src/components/molecules/_action-input/_action-input.js
  src/components/molecules/dialog/dialog-action.js
  src/components/molecules/dialog/dialog.js
  src/components/molecules/empty-state/empty-state.js
  src/components/molecules/empty-state/empty-state.md
  src/components/molecules/empty-state/empty-state.story.js
  src/components/molecules/form-group/form-group.md
  src/components/molecules/form-group/form-group.story.js
  src/components/molecules/form/actions/actions.js
  src/components/molecules/form/actions/actions.md
  src/components/molecules/form/actions/actions.story.js
  src/components/molecules/form/field/field.js
  src/components/molecules/form/field/field.md
  src/components/molecules/form/field/stories/text-field.story.js
  src/components/molecules/form/form.md
  src/components/molecules/form/form.story.js
  src/components/molecules/page-header/page-header.js
  src/components/molecules/page-header/page-header.md
  src/components/molecules/page-header/page-header.story.js
  src/components/molecules/resource-list/item/item.js
  src/components/molecules/resource-list/item/item.md
  src/components/molecules/resource-list/resource-list.js
  src/components/molecules/resource-list/resource-list.md
  src/components/molecules/resource-list/resource-list.story.js
  src/docs/spec/prop-switcher.js
  src/manage/components/client-list.js
  src/manage/pages/apis/index.js
  src/manage/pages/client-detail/advanced.js
  src/manage/pages/client-detail/settings.js
  src/manage/pages/clients/index.js
  src/manage/pages/rules/index.js
  src/manage/pages/users/index.js
  src/overview/examples/empty-states.js
  src/overview/examples/forms.js
  src/overview/examples/page-headers.js
  src/overview/examples/resource-lists.js
Labels: ⚡enhancement, 💔breaking change, 🖥️api / dx

#564 Use tokens from absolute path in helpers
  src/components/_helpers/reset.js
Labels: 🐞bug

#562 Add prop to make tooltips visible by default
  src/components/atoms/tooltip/tooltip.js
Labels: ⚡enhancement

#569 deployment-package: Lock to old serve version
  tooling/deployment-package.json
Labels: 🐞bug

#572 Merge resets into globals
  changelog.md
  package.json
  src/components/_helpers/globals.js
  src/components/_helpers/reset.js
  src/components/tokens.js
Labels: 🐞bug

#559 Standardise action shape
  src/components/_helpers/action-shape.js
  src/components/molecules/_action-input/_action-input.js
  src/components/molecules/empty-state/empty-state.js
  src/components/molecules/empty-state/empty-state.md
  src/components/molecules/empty-state/empty-state.story.js
  src/components/molecules/form/actions/actions.js
  src/components/molecules/form/field/field.js
  src/components/molecules/page-header/page-header.js
  src/components/molecules/resource-list/item/item.js
  src/components/molecules/resource-list/resource-list.js
  src/docs/spec/prop-type.js
  tooling/component-metadata.js
Labels: ⚡enhancement, 📚docs
