Repository auth0/cosmos, pull requests merged in 2018-12, with the labels that each got.

#1199 Tooling: Fix hot reload by @jvelezpo
  internal/cosmos-scripts/package.json
  package.json
  yarn.lock
Labels: 🐞bug, 🛠️ tooling

#1201 Docs: Make it easier to add a guide
  internal/docs/app.js
  internal/docs/docs-components/folding-section.js
  internal/docs/guides.js
  internal/docs/pages/contribution-guide.js
  internal/docs/pages/overriding-components.js
  internal/docs/pages/usage.js
  internal/docs/pages/usage/custom-components.js
  internal/docs/pages/usage/installation.js
  internal/docs/pages/usage/using-components.js
  internal/docs/pages/usage/with-styleguide.js
  internal/docs/sidebar/list.js
Labels: 📚docs

#1207 Improved examples in Pagination toolbar docs
  core/components/molecules/pagination-toolbar/pagination-toolbar.md
Labels: 📚docs

#1187 Tooling: Auto accept chromatic builds on master
  .storybook/config.js
  core/components/molecules/resource-list/item/item.js
  internal/cosmos-scripts/task.js
  package-scripts.js
  package.json
  tooling/chromatic.js
  yarn.lock
Labels: 🛠️ tooling

#1138 Responsive PageHeader
  core/components/molecules/page-header/description.js
  core/components/molecules/page-header/page-header.js
  core/components/molecules/page-header/page-header.md
  internal/test/unit/__snapshots__/page-header.test.js.snap
Labels: ✨enhancement

#1241 upgrade to sc-3.latest
  core/components/package.json
  yarn.lock
Labels: 🛠️ tooling

#1242 Docs: Fix folding section anchor
  internal/docs/docs-components/folding-section.js
Labels: 🐞bug, 📚docs

#1243 Removes pointer events on the overlay component
  core/components/atoms/_overlay/overlay.js
Labels: 🐞bug

#1246 Fixed accordions in Contribution guide
  internal/docs/pages/contribution-guide/architecture.js
  internal/docs/pages/contribution-guide/component-files.js
  internal/docs/pages/contribution-guide/line-height.js
  internal/docs/pages/contribution-guide/setup.js
  internal/docs/pages/contribution-guide/system-guidelines.js
  internal/docs/pages/contribution-guide/testing.js
Labels: 🐞bug, 📚docs

#1263 Implement attrs to styled API
  core/components/_helpers/component.story.js
  core/components/styled.js
Labels: ✨enhancement, 🖥️api / dx

#1273 Added key to switch elements by @tehsis (#1269)
  core/components/atoms/switch/switch.js
Labels: 🐞bug

#1276 Fix button action onClick handler not including the item
  core/components/molecules/resource-list/item/item.js
Labels: 🐞bug, 🚨hi priority

#1280 Docs: Fix broken folding links in contribution-guide
  internal/docs/docs-components/folding-section.js
Labels: 🐞bug, 📚docs

#1284 Examples: react + react-dom should have same version
  examples/manage/package.json
Labels: 🐞bug, 👩‍💻example app

#1283 Internal: Clean up code for masked TextInput
  core/components/atoms/text-input/text-input.js
Labels: 🤖internal

#1279 Internal: Replace extend with styled
  core/components/_helpers/component.story.js
  core/components/atoms/button/button.js
  core/components/atoms/heading/heading.js
  core/components/atoms/select/select.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/textarea/textarea.js
Labels: 🤖internal

#1285 Changes the Page Header from grid to flex
  core/components/molecules/page-header/description.js
  core/components/molecules/page-header/page-header.js
Labels: 🐞bug

#1192 Fixes Resource List columns
  core/components/atoms/code/code.js
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/resource-list/resource-list.md
  core/components/molecules/resource-list/resource-list.story.js
Labels: 🐞bug, 👨‍🎨design needed

#1298 Select: Removes pointer events on the icon
  core/components/atoms/select/select.js
Labels: 🐞bug

#1286 Removes line height declaration on tables
  core/components/molecules/table/table-header.js
  core/components/molecules/table/table.js
Labels: ✨enhancement

#1288 Internal: Add module to all stories
  core/components/atoms/alert/alert.story.js
  core/components/atoms/avatar/avatar.story.js
  core/components/atoms/badge/badge.story.js
  core/components/atoms/breadcrumb/breadcrumb.story.js
  core/components/atoms/button/stories/appearance.story.js
  core/components/atoms/button/stories/dark-background.story.js
  core/components/atoms/button/stories/disabled.story.js
  core/components/atoms/button/stories/icon.story.js
  core/components/atoms/button/stories/loading.story.js
  core/components/atoms/button/stories/size.story.js
  core/components/atoms/button/stories/stressed.story.js
  core/components/atoms/button/stories/success.story.js
  core/components/atoms/button/stories/wrapping.story.js
  core/components/atoms/checkbox/checkbox.story.js
  core/components/atoms/code/code.story.js
  core/components/atoms/heading/dark-background.story.js
  core/components/atoms/heading/heading.story.js
  core/components/atoms/icon/icon.story.js
  core/components/atoms/image/image.story.js
  core/components/atoms/label/label.story.js
  core/components/atoms/link/link.story.js
  core/components/atoms/logo/logo.story.js
  core/components/atoms/paragraph/paragraph.story.js
  core/components/atoms/select/select.story.js
  core/components/atoms/spinner/spinner.story.js
  core/components/atoms/switch/switch.story.js
  core/components/atoms/tag/tag.story.js
  core/components/atoms/text-input/text-input.story.js
  core/components/atoms/text/text.story.js
  core/components/atoms/textarea/text-area.story.js
  core/components/atoms/tooltip/tooltip.story.js
  core/components/molecules/_column-layout/column-layout.story.js
  core/components/molecules/_gallery-layout/gallery-layout.story.js
  core/components/molecules/_page-layout/page-layout.story.js
  core/components/molecules/_row-layout/row-layout.story.js
  core/components/molecules/avatar-block/avatar-block.story.js
  core/components/molecules/button-group/button-group.story.js
  core/components/molecules/danger-zone/danger-zone.story.js
  core/components/molecules/dialog/dialog.story.js
  core/components/molecules/empty-state/empty-state.story.js
  core/components/molecules/form-group/form-group.story.js
  core/components/molecules/form/actions/actions.story.js
  core/components/molecules/form/field/stories/select-field.story.js
  core/components/molecules/form/field/stories/switch-field.story.js
  core/components/molecules/form/field/stories/text-field.story.js
  core/components/molecules/form/field/stories/textarea-field.story.js
  core/components/molecules/form/fieldset/fieldset.story.js
  core/components/molecules/form/form.story.js
  core/components/molecules/list/list.story.js
  core/components/molecules/page-header/page-header.story.js
  core/components/molecules/pager/pager.story.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.story.js
  core/components/molecules/pagination/pagination.story.js
  core/components/molecules/resource-list/resource-list.story.js
  core/components/molecules/stack/stack.story.js
  core/components/molecules/table/table.story.js
  examples/manage/manage.story.js
Labels: 🤖internal

#1098 Sortable Resource List
  core/components/molecules/resource-list/index.js
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/resource-list/resource-list.js
  core/components/molecules/resource-list/resource-list.md
  core/components/molecules/resource-list/resource-list.story.js
  core/components/molecules/resource-list/sortable-handle.js
  core/components/package.json
  yarn.lock
Labels: 🖥️api / dx, 🙋‍♀️ user-request, 🚀 release: minor

#1281 Move actions API to Input
  core/components/_helpers/action-group-creator.js
  core/components/atoms/_input-with-actions/index.js
  core/components/atoms/_input-with-actions/input-with-actions.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/text-input/text-input.md
  core/components/atoms/text-input/text-input.story.js
  core/components/atoms/textarea/text-area.story.js
  core/components/atoms/textarea/textarea.js
  core/components/atoms/textarea/textarea.md
  core/components/components.js
  core/components/index.js
  core/components/molecules/_action-input/action-input.js
  core/components/molecules/_action-input/action-input.md
  core/components/molecules/_action-input/index.js
  core/components/molecules/dialog/dialog.js
  core/components/molecules/form/form.js
  internal/docs/spec/prop-string.js
Labels: 🖥️api / dx, 🙋‍♀️ user-request

#1312 Testing: Custom prop - Molecules
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/danger-zone/danger-zone.js
  core/components/molecules/dialog/dialog.js
  core/components/molecules/empty-state/empty-state.js
  core/components/molecules/form-group/form-group.js
  core/components/molecules/list/list.js
  core/components/molecules/page-header/page-header.js
  core/components/molecules/pager/pager.js
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination/pagination.js
  core/components/molecules/resource-list/item/item.js
  core/components/molecules/resource-list/resource-list.js
  core/components/molecules/sidebar/sidebar-link-group.js
  core/components/molecules/sidebar/sidebar-link.js
  core/components/molecules/sidebar/sidebar.js
  core/components/molecules/tabs/tabs.js
  internal/docs/pages/automation-glossary.js
  internal/test/integration/molecules/avatar-block.fixture.js
  internal/test/integration/molecules/avatar-block.test.js
  internal/test/integration/molecules/button-group.fixture.js
  internal/test/integration/molecules/button-group.test.js
  internal/test/integration/molecules/danger-zone.fixture.js
  internal/test/integration/molecules/danger-zone.test.js
  internal/test/integration/molecules/dialog.fixture.js
  internal/test/integration/molecules/dialog.test.js
  internal/test/integration/molecules/empty-state.fixture.js
  internal/test/integration/molecules/empty-state.test.js
  internal/test/integration/molecules/form-group.fixture.js
  internal/test/integration/molecules/form-group.test.js
  internal/test/integration/molecules/form.fixture.js
  internal/test/integration/molecules/form.test.js
  internal/test/integration/molecules/list.fixture.js
  internal/test/integration/molecules/list.test.js
  internal/test/integration/molecules/page-header.fixture.js
  internal/test/integration/molecules/page-header.test.js
  internal/test/integration/molecules/pager.fixture.js
  internal/test/integration/molecules/pager.test.js
  internal/test/integration/molecules/pagination-toolbar.fixture.js
  internal/test/integration/molecules/pagination-toolbar.test.js
  internal/test/integration/molecules/pagination.fixture.js
  internal/test/integration/molecules/pagination.test.js
  internal/test/integration/molecules/resource-list.fixture.js
  internal/test/integration/molecules/resource-list.test.js
  internal/test/integration/molecules/sidebar.fixture.js
  internal/test/integration/molecules/sidebar.test.js
  internal/test/integration/molecules/stack.fixture.js
  internal/test/integration/molecules/stack.test.js
  internal/test/integration/molecules/table.fixture.js
  internal/test/integration/molecules/table.test.js
  internal/test/integration/molecules/tabs.fixture.js
  internal/test/integration/molecules/tabs.test.js
  internal/test/unit/__snapshots__/empty-state.test.js.snap
  internal/test/unit/__snapshots__/tabs.test.js.snap
Labels: 👮 testing
