Repository auth0/cosmos, pull requests merged in 2018-06, with the labels that each got.

#581 Fix radio bugs
  src/components/atoms/radio/radio.js
  src/components/molecules/form/form.md
Labels: 🐞bug, 📚docs, 🖥️api / dx

#582 Fix prop warnings
  src/components/molecules/page-header/page-header.js
  src/components/molecules/sidebar/sidebar-link.js
  src/components/molecules/stack/stack.md
  src/docs/docs-components/tag.js
  src/docs/docs-components/typography.js
  src/manage/components/connection-list.js
  src/manage/components/side-navigation.js
  src/manage/pages/client-detail/advanced.js
  src/manage/pages/client-detail/connections.json
  src/manage/pages/sso-integrations/index.js
  src/overview/examples/empty-states.js
  src/overview/examples/forms.js
  src/overview/examples/resource-lists.js
  src/overview/ov-components/icon-sketch.js
Labels: ⚡enhancement, 📚docs, 🖥️api / dx

#584 Stack: Add space-between justifyContent prop value
  src/components/molecules/stack/stack.js
Labels: ⚡enhancement

#590 Page Header: show secondary action when primary is missing.
  src/components/molecules/page-header/page-header.js
  src/components/molecules/page-header/page-header.md
  src/components/molecules/page-header/page-header.story.js
Labels: 🖥️api / dx

#593 Avoid breaking docs site on specific searches
  src/docs/sidebar/children.js
Labels: 📚docs

#595 Update outdated proptypes for PageHeader
  src/components/molecules/page-header/page-header.js
  src/components/molecules/page-header/page-header.md
Labels: 📚docs, 🖥️api / dx

#586 Remove sideEffects from package.json
  src/components/package.json
Labels: 🐞bug

#587 Remove prop types from manage/ClientList
  src/manage/components/client-list.js
Labels: 🐞bug

#583 Sidebar: open folder groups when child item is selected
  src/components/molecules/sidebar/sidebar-link-group.js
  src/manage/components/side-navigation.js
Labels: ⚡enhancement

#605 Sandbox: Deploy *.stories.js not *.sketch.js
  package.json
Labels: 🐞bug

#607 Pull docs to internal
  .gitignore
  contributing.md
  internal/docs/app.js
  internal/docs/changes.js
  internal/docs/contribution-guide.js
  internal/docs/docs-components/pre.js
  internal/docs/docs-components/tag.js
  internal/docs/docs-components/typography.js
  internal/docs/faqs.js
  internal/docs/guiding-principles.js
  internal/docs/home.js
  internal/docs/index.js
  internal/docs/package.json
  internal/docs/public/index.html
  internal/docs/public/screenshots/dialog.png
  internal/docs/public/screenshots/overlay.png
  internal/docs/sidebar/children.js
  internal/docs/sidebar/group.js
  internal/docs/sidebar/index.js
  internal/docs/sidebar/link.js
  internal/docs/sidebar/list.js
  internal/docs/sidebar/logo.js
  internal/docs/sidebar/search.js
  internal/docs/spec/break.js
  internal/docs/spec/copy-button.js
  internal/docs/spec/default-props.js
  internal/docs/spec/example.js
  internal/docs/spec/get-defaults-from-code.js
  internal/docs/spec/header.js
  internal/docs/spec/icon-browser.js
  internal/docs/spec/index.js
  internal/docs/spec/page-header.js
  internal/docs/spec/playground.js
  internal/docs/spec/prop-conflicts.js
  internal/docs/spec/prop-string.js
  internal/docs/spec/prop-switcher.js
  internal/docs/spec/prop-type.js
  internal/docs/spec/props.js
  internal/docs/webpack.config.js
  package.json
  public/redirect/index.html
  src/components/atoms/button/button.md
  src/components/atoms/overlay/overlay.md
  src/components/atoms/radio/radio.md
  src/components/molecules/button-group/button-group.md
  src/components/molecules/dialog/dialog.md
  src/components/molecules/form/field/field.md
  src/components/molecules/form/form.md
  src/components/molecules/resource-list/item/item.md
  src/components/molecules/resource-list/resource-list.md
  src/docs/index.js
  src/index.js
  src/overview/ov-components/navigation.js
  tooling/component-metadata.js
  tooling/update-icons.js
  yarn.lock
Labels: ⚡enhancement, 🛠️tooling

#614 Export styled from cosmos
  .vscode/settings.json
  examples/webpack-hello-world/package.json
  src/components/styled.js
  yarn.lock
Labels: 🎨styling, 🖥️api / dx, 🛠️tooling

#617 Align tooltip on button groups.
  src/components/atoms/tooltip/tooltip.js
  src/components/molecules/button-group/button-group.js
Labels: 🎨styling

#623 welcome page by @pbarrenechea (revive #560)
  examples/manage/components/page.js
  examples/manage/components/side-navigation.js
  examples/manage/components/welcome-card.js
  examples/manage/pages/welcome/index.js
  examples/manage/public/customer-icon.svg
Labels: ☂️example app

#630 Give chromatic the right script
  package-scripts.js
  package.json
Labels: 🐞bug, 👮testing, 🛠️tooling
