Repository auth0/cosmos, pull requests merged in 2018-02, with the labels that each got.

#224 [Button] Add support for tooltips
  src/components/atoms/button/button.md
  src/components/atoms/button/index.js
  src/components/molecules/_action-input/index.js
  src/components/molecules/form/field/field.md
Labels: enhancement

#258 Documentation Tweaks Part 1
  src/components/atoms/text-input/text-input.md
  src/components/atoms/textarea/index.js
  src/components/atoms/textarea/textarea.md
  src/components/atoms/tooltip/index.js
  src/components/atoms/tooltip/tooltip.md
Labels: docs

#260 Fixed sidebar link for components with no props
  tooling/component-metadata.js
Labels: bug

#261 Button hover fix
  src/components/atoms/button/index.js
Labels: bug

#262 Remove destructive from Form.Actions proptypes and docs
  src/components/molecules/form/actions/actions.md
  src/components/molecules/form/actions/index.js
Labels: design/ux

#263 Fix alignment for Form.Actions
  src/components/molecules/form/actions/index.js
Labels: bug

#264 Add props + example for form field actiosn
  src/components/molecules/_action-input/index.js
  src/components/molecules/form/field/field.md
  src/components/molecules/form/field/index.js
Labels: bug

#194 add Link component
  src/components/atoms/link/index.js
  src/components/atoms/link/link.md
  src/components/index.js
  src/components/molecules/empty-state/index.js
  src/components/molecules/form/field/field.md
  src/components/molecules/form/form.md
  src/docs/spec/prop-switcher.js
  src/manage/advanced.js
  src/manage/settings.js
Labels: new-component

#268 Document header + paragraph
  src/components/_helpers/globals.js
  src/components/atoms/header/header.md
  src/components/atoms/header/index.js
  src/components/atoms/paragraph/index.js
  src/components/atoms/paragraph/paragraph.md
  src/components/index.js
  src/components/molecules/empty-state/index.js
  src/components/molecules/list/index.js
  src/is-cosmos-ready-yet/index.js
  src/manage/advanced.js
  src/manage/client-list.js
  src/manage/client.js
  src/manage/connections.js
  src/overview/src/container.js
  src/overview/src/typography.js
Labels: docs

#269 Add conflict handling for prop table
  src/docs/spec/prop-conflicts.js
  src/docs/spec/props.js
Labels: docs

#284 Add ButtonGroup component
  src/components/atoms/button/index.js
  src/components/index.js
  src/components/molecules/_action-input/index.js
  src/components/molecules/button-group/button-group.md
  src/components/molecules/button-group/index.js
  src/components/molecules/form/actions/index.js
  src/manage/client-list.js
  src/manage/settings.js
Labels: new-component

#280 Fix disabled state for Button
  src/components/atoms/button/index.js
Labels: bug

#281 Fix wrapping of text in docs header
  src/docs/spec/page-header.js
Labels: bug

#282 Add header for all components
  src/components/atoms/header/header.md
  src/components/atoms/icon/icon.md
  src/components/atoms/overlay/overlay.md
  src/components/atoms/select/select.md
  src/components/atoms/spinner/spinner.md
  src/components/atoms/text-input/text-input.md
  src/components/atoms/tooltip/tooltip.md
  src/components/molecules/dialog/dialog.md
  src/components/molecules/form-group/form-group.md
Labels: bug

#205 [TextInput] Add new "masked" prop to obscure hidden data
  src/components/atoms/text-input/index.js
  src/components/atoms/text-input/text-input.md
  src/manage/settings.js
Labels: enhancement

#201 Page header
  src/components/atoms/breadcrumb/index.js
  src/components/index.js
  src/components/molecules/page-header/actions.js
  src/components/molecules/page-header/description.js
  src/components/molecules/page-header/index.js
  src/manage/client-avatar.js
  src/manage/client-list.js
  src/manage/client.js
Labels: dont-merge

#291 Added the guiding principles to the docs
  src/docs/docs-components/typography.js
  src/docs/guiding-principles.js
  src/docs/home.js
  src/docs/index.js
  src/docs/sidebar/index.js
  src/docs/sidebar/list.js
Labels: docs

#297 Clean up console
  src/components/atoms/_well/index.js
  src/components/atoms/button/index.js
  src/components/atoms/code/code.md
  src/components/atoms/overlay/overlay.md
  src/components/atoms/paragraph/index.js
  src/components/atoms/text-input/index.js
  src/components/index.js
  src/components/molecules/button-group/index.js
  src/components/molecules/dialog/dialog.md
  src/components/molecules/dialog/index.js
  src/components/molecules/form-group/form-group.md
  src/components/molecules/form-group/index.js
  src/components/molecules/form/actions/actions.md
  src/components/molecules/form/actions/index.js
  src/components/molecules/form/field/field.md
  src/components/molecules/form/form.md
  src/components/molecules/sidebar/index.js
  src/docs/docs-components/pre.js
  src/docs/docs-components/tag.js
  src/docs/docs-components/typography.js
  src/docs/home.js
  src/docs/sidebar/logo.js
  src/docs/spec/default-props.js
  src/docs/spec/index.js
  src/docs/spec/prop-conflicts.js
  src/docs/spec/prop-string.js
  src/manage/components/container.js
  src/manage/components/side-navigation.js
  src/manage/components/top-navigation.js
  src/manage/index.js
  src/overview/src/buttons.js
  tooling/component-metadata.js
Labels: bug

#298 TextInput: should use defaultValue instead of value
  src/components/atoms/text-input/index.js
  src/components/atoms/text-input/text-input.md
Labels: bug

#300 Fix icon name in page header
  src/manage/client-list.js
Labels: bug

#301 Removed h5, using h4 instead
  src/components/atoms/header/header.md
  src/components/atoms/header/index.js
  src/components/molecules/list/index.js
  src/overview/src/container.js
  src/overview/src/typography.js
Labels: enhancement

#311 Button styles review
  src/components/atoms/button/index.js
  src/components/molecules/_action-input/index.js
  src/overview/src/buttons.js
  src/tokens/colors.js
Labels: design/ux

#306 Hide label for switch in POC, right-align Switches and ButtonGroups
  src/manage/client-list.js
  src/manage/connections.js
Labels: bug

#310 Fixed copy code again
  src/docs/spec/copy-button.js
Labels: bug

#313 Added a new navigation and layout for the PoC Overview of Components
  public/docs.png
  public/github.png
  public/icon-sketch.svg
  src/icons/icon-hourglass.svg
  src/overview/examples/buttons.js
  src/overview/examples/colors.js
  src/overview/examples/empty-states.js
  src/overview/examples/forms.js
  src/overview/examples/icons.js
  src/overview/examples/inputs.js
  src/overview/examples/lists.js
  src/overview/examples/overlays.js
  src/overview/examples/page-headers.js
  src/overview/examples/spacing.js
  src/overview/examples/tabs.js
  src/overview/examples/tooltip.js
  src/overview/examples/typography.js
  src/overview/index.js
  src/overview/ov-components/container.js
  src/overview/ov-components/example.js
  src/overview/ov-components/grid.js
  src/overview/ov-components/icon-sketch.js
  src/overview/ov-components/navigation.js
  src/overview/ov-components/overview.js
  src/overview/ov-components/section.js
  src/overview/ov-components/stack.js
  src/overview/src/empty-states.js
  src/overview/src/forms.js
  src/overview/src/links.js
  src/overview/src/overview.js
  src/overview/src/tooltip.js
Labels: design/ux

#317 Added pages for usage and contribution
  src/docs/contribution-guide.js
  src/docs/docs-components/pre.js
  src/docs/home.js
  src/docs/index.js
  src/docs/sidebar/list.js
Labels: docs

#319 Added default line-height and margin to Headings
  src/components/atoms/heading/index.js
  src/components/atoms/paragraph/index.js
  src/components/molecules/empty-state/index.js
  src/components/molecules/list/index.js
  src/components/molecules/page-header/index.js
Labels: design/ux

#321 Small tweaks for the PoC
  src/components/atoms/button/index.js
  src/components/atoms/paragraph/index.js
  src/components/atoms/switch/index.js
  src/components/molecules/form/fieldset/divider.js
  src/overview/examples/buttons.js
  src/overview/examples/colors.js
  src/overview/examples/forms.js
  src/overview/examples/inputs.js
  src/overview/examples/lists.js
  src/overview/examples/logos.js
  src/overview/examples/spacing.js
  src/overview/examples/typography.js
  src/overview/index.js
  src/overview/ov-components/example.js
  src/overview/ov-components/grid.js
Labels: design/ux

#332 Added Title case for ‘Cosmos’
  src/docs/contribution-guide.js
  src/docs/sidebar/list.js
Labels: docs
