Repository auth0/cosmos, pull requests merged in 2019-01, with the labels that each got.

#1375 Quick aria labels fix for Tabs
  core/components/molecules/tabs/tabs.js
  internal/test/unit/__snapshots__/tabs.test.js.snap
Labels: 🐞bug

#1244 Image size
  core/components/atoms/avatar/avatar.js
  core/components/atoms/avatar/avatar.story.js
  core/components/atoms/image/image.js
  core/components/atoms/image/image.md
  core/components/atoms/image/image.story.js
  internal/docs/public/main.7cd4853f1ba2a3b81b63.js
Labels: ✨enhancement

#1387 Fix security alerts for packages
  core/components/package.json
  examples/perf-tests/package.json
  examples/webpack-hello-world/package.json
  internal/cosmos-scripts/package.json
  internal/docs/package.json
  yarn.lock
Labels: 🐞bug

#1391 Fixed chevron up not facing up
  core/components/atoms/icon/icons.json
  core/icons/icon-chevron-up.svg
Labels: 🐞bug

#1393 Fixed rendering of label for Radio and Form.Radio (with tests)
  core/components/atoms/radio/radio.js
  core/components/atoms/radio/radio.story.js
  core/components/molecules/form/field/stories/radio-field.story.js
Labels: 🐞bug, 👮 testing, 🚨hi priority

#1398 adds browserstack badge
  readme.md
Labels: 📚docs

#1401 Add icon “application”
  core/components/atoms/icon/icons.json
  core/icons/icon-application.svg
Labels: 🚨hi priority

#1412 use insertBefore instead of prepend
  core/components/_helpers/globals.js
Labels: 🐞bug

#1411 Replaces the default value of the form label to be an empty string
  core/components/molecules/form/field/field.js
  core/components/molecules/form/field/stories/radio-field.story.js
  internal/test/unit/__snapshots__/form-field.test.js.snap
Labels: 🐞bug

#1287 Implement Form.Field API based on RFC
  core/components/molecules/dialog/dialog.story.js
  core/components/molecules/form-group/form-group.md
  core/components/molecules/form-group/form-group.story.js
  core/components/molecules/form/actions/actions.md
  core/components/molecules/form/field/field.md
  core/components/molecules/form/field/stories/field.story.js
  core/components/molecules/form/field/stories/select-field.story.js
  core/components/molecules/form/field/stories/switch-field.story.js
  core/components/molecules/form/field/stories/text-field.story.js
  core/components/molecules/form/field/stories/textarea-field.story.js
  core/components/molecules/form/fieldset/fieldset.md
  core/components/molecules/form/fieldset/fieldset.story.js
  core/components/molecules/form/form.md
Labels: 🎨 style, 🖥️api / dx

#1363 Introduces Stack Layout
  core/components/components.js
  core/components/index.js
  core/components/molecules/_gallery-layout/gallery-layout.js
  core/components/molecules/_stack-layout/index.js
  core/components/molecules/_stack-layout/stack-layout.js
  core/components/molecules/_stack-layout/stack-layout.md
  core/components/molecules/_stack-layout/stack-layout.story.js
Labels: ✨enhancement

#1397 Quick and dirty release guide
  internal/docs/pages/contribution-guide.js
  internal/docs/pages/contribution-guide/release-process.js
Labels: 📚docs

#1423 Update sidebar-link-group.js (#1420)
  core/components/molecules/sidebar/sidebar-link-group.js
Labels: 🐞bug

#1435 Docs: Add prop replacement right next to deprecated prop
  core/components/atoms/alert/alert.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/textarea/textarea.js
  core/components/molecules/avatar-block/avatar-block.js
  core/components/molecules/empty-state/empty-state.js
  internal/docs/spec/props.js
  package.json
  yarn.lock
Labels: 📚docs, 🖥️api / dx

#1449 Makes the switch have a consistent width
  core/components/atoms/switch/switch.js
Labels: ✨enhancement

#1459 Add event handler tests for molecules
  core/components/molecules/pagination-toolbar/pagination-toolbar.js
  core/components/molecules/pagination/pagination.js
  internal/test/integration/molecules/dialog.fixture.js
  internal/test/integration/molecules/dialog.test.js
  internal/test/integration/molecules/form.fixture.js
  internal/test/integration/molecules/form.test.js
  internal/test/integration/molecules/page-header.fixture.js
  internal/test/integration/molecules/page-header.test.js
  internal/test/integration/molecules/pager.fixture.js
  internal/test/integration/molecules/pager.test.js
  internal/test/integration/molecules/pagination-toolbar.fixture.js
  internal/test/integration/molecules/pagination-toolbar.test.js
  internal/test/integration/molecules/pagination.fixture.js
  internal/test/integration/molecules/pagination.test.js
  internal/test/integration/molecules/table.fixture.js
  internal/test/integration/molecules/table.test.js
Labels: ♿ accessibility, 👮 testing

#1372 Accessible tooltip
  core/components/atoms/tooltip/tooltip.js
  core/components/atoms/tooltip/tooltip.story.js
  internal/test/integration/atoms/tooltip.fixture.js
  internal/test/integration/atoms/tooltip.test.js
Labels: ♿ accessibility, 👮 testing
