Repository auth0/cosmos, pull requests merged in 2019-02, with the labels that each got.

#1473 Fix checkbox event firing twice
  core/components/atoms/checkbox/checkbox.js
  internal/test/integration/atoms/checkbox.test.js
  internal/test/unit/checkbox.test.js
Labels: 🐞bug, 🚨hi priority

#1490 Start migration guide
  internal/docs/guides.js
  internal/docs/pages/migration-guide.js
Labels: 📚docs

#1458 [DXDP-88] Composable actions for Tabs in Dialog
  core/components/atoms/tooltip/tooltip.js
  core/components/molecules/dialog/dialog.js
  core/components/molecules/dialog/dialog.md
  core/components/molecules/dialog/dialog.story.js
  internal/test/integration/molecules/dialog-composed.fixture.js
  internal/test/integration/molecules/dialog.test.js
Labels: 🤔 RFC / Proposal

#1493 Fixed selected color for Link group and added basic stories
  core/components/molecules/sidebar/sidebar-link-group.js
  core/components/molecules/sidebar/sidebar.story.js
Labels: 🐞bug

#1495 Fixed typo in icon ‘brand-weibo’
  core/components/atoms/icon/icons.json
  core/icons/brands/brand-weibo.svg
Labels: 🐞bug

#1500 Fix sidebar not changing styles when selected link prop changed
  core/components/molecules/sidebar/sidebar-link-group.js
  core/components/molecules/sidebar/sidebar.story.js
Labels: Internal Test OK

#1510 Layouts in docs
  core/components/components.js
  core/components/layouts/_app-layout/app-layout.js
  core/components/layouts/_app-layout/app-layout.story.js
  core/components/layouts/_app-layout/index.js
  core/components/layouts/column-layout/column-layout.js
  core/components/layouts/column-layout/column-layout.md
  core/components/layouts/column-layout/column-layout.story.js
  core/components/layouts/column-layout/index.js
  core/components/layouts/gallery-layout/gallery-layout.js
  core/components/layouts/gallery-layout/gallery-layout.md
  core/components/layouts/gallery-layout/gallery-layout.story.js
  core/components/layouts/gallery-layout/index.js
  core/components/layouts/page-layout/index.js
  core/components/layouts/page-layout/page-layout.js
  core/components/layouts/page-layout/page-layout.md
  core/components/layouts/page-layout/page-layout.story.js
  core/components/layouts/row-layout/index.js
  core/components/layouts/row-layout/row-layout.js
  core/components/layouts/row-layout/row-layout.md
  core/components/layouts/row-layout/row-layout.story.js
  core/components/layouts/stack-layout/index.js
  core/components/layouts/stack-layout/stack-layout.js
  core/components/layouts/stack-layout/stack-layout.md
  core/components/layouts/stack-layout/stack-layout.story.js
  internal/docs/sidebar/group.js
  internal/docs/sidebar/list.js
  tooling/component-metadata.js
Labels: 📚docs

#1505 Image API: support src instead
  core/components/atoms/image/image.js
Labels: ⚠️ release: soft deprecation, 🖥️api / dx

#1506 Switch: change onToggle to onChange
  core/components/atoms/switch/switch.js
  core/components/atoms/switch/switch.md
  core/components/atoms/switch/switch.story.js
  internal/docs/pages/migration-guide.js
  internal/test/integration/atoms/switch.fixture.js
  internal/test/integration/atoms/switch.test.js
Labels: ⚠️ release: soft deprecation, 🖥️api / dx

#1439 Automatically add id inside form fields
  core/components/atoms/checkbox/checkbox.js
  core/components/atoms/checkbox/checkbox.story.js
  core/components/atoms/radio/radio.js
  core/components/atoms/radio/radio.story.js
  core/components/atoms/select/select.js
  core/components/atoms/switch/switch.js
  core/components/atoms/text-input/text-input.js
  core/components/atoms/textarea/textarea.js
  core/components/molecules/form/field/field.js
  core/components/molecules/form/field/field.md
  core/components/molecules/form/field/stories/field.story.js
  core/components/molecules/form/field/stories/select-field.story.js
  core/components/molecules/form/form.js
  core/components/molecules/form/form.md
  core/components/molecules/page-header/page-header.js
  internal/cosmos-scripts/configs/webpack.development.config.js
  internal/test/integration/automation-attributes.test.js
  internal/test/integration/helpers/automation-attribute.js
  internal/test/unit/__snapshots__/form-field.test.js.snap
  internal/test/unit/automation-attributes.test.js
Labels: ♿ accessibility, 🐞bug

#1513 Docs: Tiny addition for authoring new guides
  internal/docs/pages/contribution-guide.js
  internal/docs/pages/contribution-guide/authoring-guides.js
Labels: 📚docs, 🤖internal

#1514 Docs: Document build pipeline
  internal/docs/pages/contribution-guide.js
  internal/docs/pages/contribution-guide/build-pipeline.js
Labels: 📚docs, 🤖internal

#1528 [DXDP-183] Conditional select
  core/components/atoms/_simple-select/index.js
  core/components/atoms/_simple-select/simple-select.js
  core/components/atoms/select/select.js
  core/components/atoms/select/select.md
  core/components/atoms/select/select.story.js
  internal/test/unit/__snapshots__/form-field.test.js.snap
Labels: Internal Test OK
